#!/usr/bin/env python3
"""
Build the Stolpersteine (struikelstenen) graph for Nijmegen.

Source: the Dutch Wikipedia list "Lijst van Stolpersteine in Nijmegen" (CC BY-SA),
which has one row per stone — name, inscription (incl. fate), address, a photo on
Wikimedia Commons, and for some an explicit OSM coordinate. Stones without an
explicit coordinate are geocoded from their address via the official Dutch PDOK
Locatieserver. Wikidata carries no individual Nijmegen stones, so it is not used.

Output: backend/src/main/resources/graph/stolpersteine.ttl — pure instance triples
using the existing ontology (nmg:Stolperstein + a few generic datatype props), so
nothing else needs to change. Re-runnable; overwrites the TTL.
"""
import json
import re
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

UA = {"User-Agent": "NijmegenMap/0.1 (https://nijmegenkaart.nl; research)"}
WIKI = "https://nl.wikipedia.org/w/api.php"
PDOK = "https://api.pdok.nl/bzk/locatieserver/search/v3_1/free"
OUT = Path(__file__).parent / "backend/src/main/resources/graph/stolpersteine.ttl"
TITLE = "Lijst van Stolpersteine in Nijmegen"


def get_json(url):
    return json.load(urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=60))


def fetch_wikitext():
    q = urllib.parse.urlencode({
        "action": "query", "prop": "revisions", "rvprop": "content",
        "rvslots": "main", "titles": TITLE, "format": "json",
    })
    page = next(iter(get_json(WIKI + "?" + q)["query"]["pages"].values()))
    return page["revisions"][0]["slots"]["main"]["*"]


def clean(s):
    s = re.sub(r"<ref.*?</ref>", "", s, flags=re.DOTALL)
    s = re.sub(r"<br\s*/?>", " / ", s)
    s = re.sub(r"<[^>]+>", "", s)
    s = re.sub(r"\s*(/\s*)+", " / ", s)
    return re.sub(r"[ \t]+", " ", s).strip(" /").strip()


def parse(txt):
    table = txt[txt.find("{|"):]
    stones = []
    for row in re.split(r"\n\|-", table):
        sn = re.search(r"SortNaam\|([^|}]*)\|([^|}]*)", row)
        if not sn:
            continue
        name = f"{sn.group(1).strip()} {sn.group(2).strip()}".strip()
        life = re.search(r"\}\}'*\s*\(([\d?]{1,4}[-–][\d?]{0,4})\)", row)
        coord = re.search(r"mlat=([\d.]+)&mlon=([\d.]+)", row)
        img = re.search(r"Bestand:\s*([^|\]]+?\.jpg)", row)
        ins = re.search(r'text-align:center;"\|\s*(.+?)(?:\s*\|\||\n\|)', row, re.DOTALL)
        # Address: prefer the photo filename ("… (1886-1942), Begijnenstraat 11, Nijmegen.jpg"),
        # else the table cell right before the person column.
        addr = None
        if img:
            m = re.search(r"\([^)]*\),\s*(.+?),\s*Nijmegen", img.group(1))
            if m:
                addr = m.group(1).strip()
        if not addr:
            m = re.search(r"\|\s*([^|\n]+?)\s*\|\s*'''\{\{SortNaam", row)
            if m:
                addr = re.split(r"<br|\[", m.group(1))[0]
                addr = re.sub(r"<[^>]+>", "", addr).strip()
        stones.append({
            "name": name,
            "life": life.group(1).replace("–", "-") if life else None,
            "addr": addr,
            "lat": coord.group(1) if coord else None,
            "long": coord.group(2) if coord else None,
            "img": img.group(1).strip() if img else None,
            "inscription": clean(ins.group(1)) if ins else None,
        })
    return stones


def geocode(addr, cache):
    if addr in cache:
        return cache[addr]
    q = urllib.parse.urlencode({"q": f"{addr}, Nijmegen", "fq": "type:adres",
                                "rows": "1", "fl": "centroide_ll"})
    try:
        docs = get_json(PDOK + "?" + q)["response"]["docs"]
        ll = re.search(r"POINT\(([\d.]+) ([\d.]+)\)", docs[0]["centroide_ll"]) if docs else None
        cache[addr] = (ll.group(2), ll.group(1)) if ll else None  # (lat, lon)
    except Exception as e:
        print(f"  ! geocode failed for {addr!r}: {e}", file=sys.stderr)
        cache[addr] = None
    time.sleep(0.1)  # be polite
    return cache[addr]


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def commons_thumb(filename):
    name = filename.replace(" ", "_")
    return f"https://commons.wikimedia.org/wiki/Special:FilePath/{urllib.parse.quote(name)}?width=320"


def main():
    print("Fetching Wikipedia list…")
    stones = parse(fetch_wikitext())
    print(f"Parsed {len(stones)} stones ({sum(1 for s in stones if s['lat'])} with explicit coords)")

    cache = {}
    geocoded = 0
    for s in stones:
        if not s["lat"] and s["addr"]:
            ll = geocode(s["addr"], cache)
            if ll:
                s["lat"], s["long"] = ll
                geocoded += 1
    placed = [s for s in stones if s["lat"]]
    print(f"Geocoded {geocoded} more; {len(placed)}/{len(stones)} stones placed")

    lines = [
        "# Stolpersteine (struikelstenen) in Nijmegen — one instance per stone.",
        "# Generated by fetch_stolpersteine.py from the Dutch Wikipedia list",
        "# 'Lijst van Stolpersteine in Nijmegen' (CC BY-SA); coordinates from PDOK.",
        "# Pure instance triples on the existing ontology (nmg:Stolperstein).",
        "@prefix nmg:    <https://nijmegenkaart.nl/ns#> .",
        "@prefix id:     <https://nijmegenkaart.nl/id/> .",
        "@prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#> .",
        "@prefix owl:    <http://www.w3.org/2002/07/owl#> .",
        "",
    ]
    for i, s in enumerate(placed, 1):
        parts = [
            f"id:stolp_{i:03d} a nmg:Stolperstein",
            f'rdfs:label "{esc(s["name"])}"',
            f'nmg:lat {s["lat"]} ; nmg:long {s["long"]}',
            "nmg:about id:deportatie",
        ]
        if s["life"]:
            parts.append(f'nmg:lifespan "{esc(s["life"])}"')
        if s["addr"]:
            parts.append(f'nmg:address "{esc(s["addr"])}"')
        if s["inscription"]:
            parts.append(f'nmg:verbatim "{esc(s["inscription"])}"')
        if s["img"]:
            parts.append(f'nmg:image "{commons_thumb(s["img"])}"')
        lines.append(" ;\n    ".join(parts) + " .")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({len(placed)} stones)")


if __name__ == "__main__":
    main()
