"""
Turtle serializer: walk the model registries and render the instance `.ttl`
files (places, sources, overlays, one per chapter). Pure string assembly — no
RDF library — so the only dependency is the standard library.

Labels for sources come from the fetched credit line in data/images/credits.json
when present (full Commons attribution), else are composed from the catalog
caption + creator + licence short name. Licence IRI and rights always come from
the catalog, so the graph is valid and the bibliography correct even before any
media is fetched.
"""
from . import model as m

PREFIXES = {
    "places": ["nmg", "id", "owl", "rdfs", "wd"],
    "sources": ["nmg", "id", "schema", "dct", "owl", "rdfs", "xsd", "wd"],
    "overlays": ["nmg", "id", "rdfs"],
    "chapter": ["nmg", "id", "schema", "dct", "owl", "rdfs", "xsd", "wd"],
}
_NS = {
    "nmg": "https://nijmegenkaart.nl/ns#",
    "id": "https://nijmegenkaart.nl/id/",
    "schema": "http://schema.org/",
    "crm": "http://www.cidoc-crm.org/cidoc-crm/",
    "prov": "http://www.w3.org/ns/prov#",
    "cito": "http://purl.org/spar/cito/",
    "dct": "http://purl.org/dc/terms/",
    "geo": "http://www.w3.org/2003/01/geo/wgs84_pos#",
    "owl": "http://www.w3.org/2002/07/owl#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "wd": "http://www.wikidata.org/entity/",
}


# ---------------------------------------------------------------- literals
def _esc(s: str) -> str:
    return (s.replace("\\", "\\\\").replace('"', '\\"')
             .replace("\n", "\\n").replace("\r", ""))

def lit(s, lang=None):
    out = f'"{_esc(s)}"'
    return out + (f"@{lang}" if lang else "")

def year(y):    return f'"{y}"^^xsd:gYear'
def date(d):    return f'"{d}"^^xsd:date'
def dec(x):     return repr(float(x))
def num(n):     return str(int(n))


def _header(comment, kinds):
    lines = [f"# {comment}", "# Generated by datacollect (graph stage) — edit the",
             "# Python catalog, not this file."]
    for p in PREFIXES[kinds]:
        lines.append(f"@prefix {p}:{' ' * (7 - len(p))}<{_NS[p]}> .")
    lines.append("")
    return "\n".join(lines)


def _stmt(subject, pairs):
    """`subject a … ; p o ; … .` with one predicate per indented line."""
    body = " ;\n    ".join(f"{p} {o}" for p, o in pairs)
    return f"{subject} {body} ."


# ---------------------------------------------------------------- places
def places_ttl():
    out = [_header("Canonical places — the single source of truth for every "
                   "located point.", "places")]
    for p in m.PLACES.values():
        pairs = [("a", f"nmg:{p.cls}"), ("rdfs:label", lit(p.label, "nl")),
                 ("nmg:lat", dec(p.lat)), ("nmg:long", dec(p.long))]
        if p.same_as:
            pairs.append(("owl:sameAs", f"wd:{p.same_as}"))
        out.append(_stmt(f"id:{p.slug}", pairs))
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------- sources
def _credit_label(s, credits):
    fetched = credits.get(s.slug)
    if fetched:
        return fetched
    tail = ", ".join(x for x in (s.creator, s.license[1] if s.license else None) if x)
    base = s.caption
    if tail:
        base += f" — {tail}" + (" (Wikimedia Commons)" if s.commons else "")
    return base

def sources_ttl(credits):
    out = [_header("Canonical sources — photographs, recordings and diaries the "
                   "chapters reference by id:src_<slug>.", "sources")]
    for s in m.SOURCES.values():
        pairs = [("a", f"nmg:{s.kind}"),
                 ("rdfs:label", lit(_credit_label(s, credits), "nl"))]
        if s.media_path:
            pairs.append(("nmg:mediaPath", lit(s.media_path)))
        if s.about:
            verb = "nmg:documents" if s.kind == "AudioRecording" else "nmg:depicts"
            pairs.append((verb, f"id:{s.about}"))
        if s.creator:
            pairs.append(("dct:creator", lit(s.creator)))
        if s.authored_by:
            pairs.append(("nmg:authoredBy", f"id:{s.authored_by}"))
        if s.license:
            pairs.append(("dct:license", f"<{s.license[0]}>"))
        if s.rights:
            pairs.append(("nmg:rightsClass", lit(s.rights)))
        if s.same_as:
            pairs.append(("owl:sameAs", f"wd:{s.same_as}"))
        out.append(_stmt(f"id:src_{s.slug}", pairs))
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------- overlays
def overlays_ttl():
    out = [_header("Polygon overlays — a MapState references one via nmg:overlay; "
                   "the key selects the frontend OverlayDef.", "overlays")]
    for o in m.OVERLAYS.values():
        out.append(_stmt(f"id:overlay_{o.key}",
                         [("a", "nmg:PolygonOverlay"),
                          ("nmg:overlayKey", lit(o.key)),
                          ("rdfs:label", lit(o.label, "nl"))]))
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------- chapters
_BLOCK_TYPE = {
    "Narrative": "nmg:NarrativeBlock", "Image": "nmg:ImageBlock",
    "Gallery": "nmg:GalleryBlock", "Audio": "nmg:AudioBlock",
    "Quote": "nmg:QuoteBlock", "MemorialWall": "nmg:MemorialWallBlock",
}

def _map_pairs(mp: m.Map):
    pairs = []
    if mp.overlay:
        pairs.append(("nmg:overlay", f"id:overlay_{mp.overlay}"))
    if mp.base is not None:
        pairs.append(("nmg:baseYear", year(mp.base)))
    if mp.level is not None:
        pairs.append(("nmg:overlayLevel", num(mp.level)))
    if mp.dim:
        pairs.append(("nmg:overlayDim", "true"))
    if mp.fort is not None:
        pairs.append(("nmg:fortLevel", year(mp.fort)))
    if mp.memorial:
        pairs.append(("nmg:showMemorial", "true"))
    if mp.wall:
        pairs.append(("nmg:showWall", "true"))
    if mp.heritage:
        pairs.append(("nmg:showHeritage", "true"))
        for cat in mp.heritage_cats:
            pairs.append(("nmg:heritageCategory", lit(cat)))
        if mp.heritage_before is not None:
            pairs.append(("nmg:heritageBefore", year(mp.heritage_before)))
        if mp.heritage_after is not None:
            pairs.append(("nmg:heritageAfter", year(mp.heritage_after)))
    if mp.wikidata:
        pairs.append(("nmg:showWikidataLayer", lit(mp.wikidata)))
        # heritage_cats / heritage_before / heritage_after double as this layer's
        # filters (reusing the same ontology predicates — see nmg:showWikidataLayer).
        for cat in mp.heritage_cats:
            pairs.append(("nmg:heritageCategory", lit(cat)))
        if mp.heritage_before is not None:
            pairs.append(("nmg:heritageBefore", year(mp.heritage_before)))
        if mp.heritage_after is not None:
            pairs.append(("nmg:heritageAfter", year(mp.heritage_after)))
    if mp.focus:
        pairs.append(("nmg:focusPlace", " , ".join(f"id:{f}" for f in mp.focus)))
    if mp.arrows:
        pairs.append(("nmg:arrow", " , ".join(
            f"id:arrow_{a.frm}_{a.to}" for a in mp.arrows)))
    if mp.pins:
        pairs.append(("nmg:photoPin", " , ".join(
            f"id:pin_{p.place}" for p in mp.pins)))
    return pairs

def _block_pairs(b: m.Block):
    pairs = [("a", _BLOCK_TYPE[b.kind])]
    if b.text is not None:
        pairs.append(("schema:text", lit(b.text, "nl")))
    if b.about:
        pairs.append(("nmg:about", f"id:{b.about}"))
    if b.cites:
        pairs.append(("nmg:cites", f"id:src_{b.cites}"))
    if b.src:
        pairs.append(("nmg:references", f"id:src_{b.src}"))
    if b.ref:
        pairs.append(("nmg:references", f"id:{b.ref}"))
    return pairs

def chapter_ttl(ch: m.Chapter):
    out = [_header(ch.comment, "chapter")]

    # actors / events / quotes defined in this file (referenced by segments)
    for a in ch.actors:
        pairs = [("a", f"nmg:{a.cls}"), ("rdfs:label", lit(a.label, a.lang))]
        if a.same_as:
            pairs.append(("owl:sameAs", f"wd:{a.same_as}"))
        out.append(_stmt(f"id:{a.slug}", pairs))
    for e in ch.events:
        pairs = [("a", "nmg:Event"), ("rdfs:label", lit(e.label, "nl"))]
        if e.date:
            pairs.append(("nmg:startDate", date(e.date)))
        if e.same_as:
            pairs.append(("owl:sameAs", f"wd:{e.same_as}"))
        if e.part_of:
            pairs.append(("nmg:partOf", f"id:{e.part_of}"))
        if e.at:
            pairs.append(("nmg:occurredAt", " , ".join(f"id:{p}" for p in e.at)))
        for who in e.participants:
            pairs.append(("nmg:hadParticipant", f"id:{who}"))
        out.append(_stmt(f"id:{e.slug}", pairs))
    for q in ch.quotes:
        pairs = [("a", "nmg:Quote"),
                 ("nmg:derivedFrom", f"id:src_{q.derived_from}")]
        if q.about:
            pairs.append(("nmg:about", f"id:{q.about}"))
        if q.locator:
            pairs.append(("nmg:locator", lit(q.locator)))
        pairs.append(("dct:language", lit(q.lang)))
        pairs.append(("nmg:verbatim", lit(q.verbatim)))
        out.append(_stmt(f"id:{q.slug}", pairs))

    # story
    s = ch.story
    spairs = [("a", "nmg:Story"), ("rdfs:label", lit(s.label, "nl")),
              ("nmg:introText", lit(s.intro, "nl")),
              ("nmg:eraLabel", lit(s.era, "nl")),
              ("nmg:representativeYear", year(s.year)),
              ("nmg:storyOrder", num(s.order))]
    if s.tag:
        spairs.insert(5, ("nmg:tag", lit(s.tag)))
    spairs.append(("nmg:hasThread",
                   " ,\n        ".join(f"id:thread_{t.key}" for t in ch.threads)))
    out.append(_stmt(f"id:story_{s.slug}", spairs))

    # threads + their segments
    for t in ch.threads:
        out.append(_stmt(f"id:thread_{t.key}",
                         [("a", "nmg:Thread"), ("rdfs:label", lit(t.label, "nl")),
                          ("nmg:order", num(t.order)),
                          ("nmg:hasSegment",
                           " , ".join(f"id:seg_{sg.key}" for sg in t.segments))]))
        for sg in t.segments:
            seg_pairs = [("a", "nmg:Segment"), ("nmg:order", num(sg.order)),
                         ("nmg:tickLabel", lit(sg.tick))]
            if sg.event:
                seg_pairs.append(("nmg:primaryEvent", f"id:{sg.event}"))
            if sg.map is not None:
                seg_pairs.append(("nmg:mapState", f"id:map_{sg.key}"))
            seg_pairs.append(("nmg:hasBlock",
                              " , ".join(f"id:block_{sg.key}_{i}"
                                         for i in range(1, len(sg.blocks) + 1))))
            out.append(_stmt(f"id:seg_{sg.key}", seg_pairs))

            if sg.map is not None:
                out.append(_stmt(f"id:map_{sg.key}",
                                 [("a", "nmg:MapState")] + _map_pairs(sg.map)))
                for a in sg.map.arrows:
                    out.append(_stmt(f"id:arrow_{a.frm}_{a.to}",
                                     [("a", "nmg:Arrow"),
                                      ("nmg:arrowFrom", f"id:{a.frm}"),
                                      ("nmg:arrowTo", f"id:{a.to}"),
                                      ("nmg:arrowLabel", lit(a.label)),
                                      ("nmg:arrowCurve", dec(a.curve))]))
                for p in sg.map.pins:
                    out.append(_stmt(f"id:pin_{p.place}",
                                     [("a", "nmg:PhotoPin"),
                                      ("nmg:atPlace", f"id:{p.place}"),
                                      ("nmg:references", f"id:src_{p.src}"),
                                      ("schema:text", lit(p.text, "nl"))]))

            for i, b in enumerate(sg.blocks, 1):
                bp = _block_pairs(b)              # [("a", Type), …]
                out.append(_stmt(f"id:block_{sg.key}_{i}",
                                 [bp[0], ("nmg:order", num(i))] + bp[1:]))
    return "\n".join(out) + "\n"
