"""
Stolpersteine stage: build the struikelstenen graph for Nijmegen as instance
triples on the existing ontology.

Source: the Dutch Wikipedia list "Lijst van Stolpersteine in Nijmegen" (CC BY-SA),
one row per stone — name, inscription, address, a Commons photo, and for some an
explicit OSM coordinate. Stones without a coordinate are geocoded via PDOK.

Output: backend/.../graph/stolpersteine.ttl. Re-runnable; overwrites the TTL.
A single, self-contained build (no catalog content).
"""
import re

from ..core import BACKEND_GRAPH, Stage, register_stage
from ..sources import commons, pdok, wikipedia

TITLE = "Lijst van Stolpersteine in Nijmegen"
OUT = BACKEND_GRAPH / "stolpersteine.ttl"


def _clean(s):
    s = re.sub(r"<ref.*?</ref>", "", s, flags=re.DOTALL)
    s = re.sub(r"<br\s*/?>", " / ", s)
    s = re.sub(r"<[^>]+>", "", s)
    s = re.sub(r"\s*(/\s*)+", " / ", s)
    return re.sub(r"[ \t]+", " ", s).strip(" /").strip()


def _parse(txt):
    table = txt[txt.find("{|"):]
    stones = []
    for row in re.split(r"\n\|-", table):
        sn = re.search(r"SortNaam\|([^|}]*)\|([^|}]*)", row)
        if not sn:
            continue
        name = f"{sn.group(1).strip()} {sn.group(2).strip()}".strip()
        life = re.search(r"\}\}'*\s*\(([\d?]{1,4}[-–][\d?]{0,4})\)", row)
        coord = re.search(r"mlat=([\d.]+)&mlon=([\d.]+)", row)
        img = re.search(r"Bestand:\s*([^|\]]+?\.jpg)", row)
        ins = re.search(r'text-align:center;"\|\s*(.+?)(?:\s*\|\||\n\|)', row, re.DOTALL)
        # Address: prefer the photo filename, else the cell before the person column.
        addr = None
        if img:
            m = re.search(r"\([^)]*\),\s*(.+?),\s*Nijmegen", img.group(1))
            if m:
                addr = m.group(1).strip()
        if not addr:
            m = re.search(r"\|\s*([^|\n]+?)\s*\|\s*'''\{\{SortNaam", row)
            if m:
                addr = re.split(r"<br|\[", m.group(1))[0]
                addr = re.sub(r"<[^>]+>", "", addr).strip()
        stones.append({
            "name": name,
            "life": life.group(1).replace("–", "-") if life else None,
            "addr": addr,
            "lat": coord.group(1) if coord else None,
            "long": coord.group(2) if coord else None,
            "img": img.group(1).strip() if img else None,
            "inscription": _clean(ins.group(1)) if ins else None,
        })
    return stones


def _esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


@register_stage
class StolpersteineStage(Stage):
    name = "stolpersteine"
    help = "Stolpersteine TTL from Wikipedia + PDOK -> backend graph"

    def run(self, args):
        print("  Fetching Wikipedia list…")
        stones = _parse(wikipedia.wikitext(TITLE))
        print(f"  Parsed {len(stones)} stones "
              f"({sum(1 for s in stones if s['lat'])} with explicit coords)")

        cache, geocoded = {}, 0
        for s in stones:
            if not s["lat"] and s["addr"]:
                ll = pdok.geocode(s["addr"], cache)
                if ll:
                    s["lat"], s["long"] = ll
                    geocoded += 1
        placed = [s for s in stones if s["lat"]]
        print(f"  Geocoded {geocoded} more; {len(placed)}/{len(stones)} stones placed")

        lines = [
            "# Stolpersteine (struikelstenen) in Nijmegen — one instance per stone.",
            "# Generated by datacollect (stolpersteine stage) from the Dutch Wikipedia",
            "# list 'Lijst van Stolpersteine in Nijmegen' (CC BY-SA); coords from PDOK.",
            "# Pure instance triples on the existing ontology (nmg:Stolperstein).",
            "@prefix nmg:    <https://nijmegenkaart.nl/ns#> .",
            "@prefix id:     <https://nijmegenkaart.nl/id/> .",
            "@prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#> .",
            "@prefix owl:    <http://www.w3.org/2002/07/owl#> .",
            "",
        ]
        for i, s in enumerate(placed, 1):
            parts = [
                f"id:stolp_{i:03d} a nmg:Stolperstein",
                f'rdfs:label "{_esc(s["name"])}"',
                f'nmg:lat {s["lat"]} ; nmg:long {s["long"]}',
                "nmg:about id:deportatie",
            ]
            if s["life"]:
                parts.append(f'nmg:lifespan "{_esc(s["life"])}"')
            if s["addr"]:
                parts.append(f'nmg:address "{_esc(s["addr"])}"')
            if s["inscription"]:
                parts.append(f'nmg:verbatim "{_esc(s["inscription"])}"')
            if s["img"]:
                parts.append(f'nmg:image "{commons.filepath_thumb(s["img"], 320)}"')
            lines.append(" ;\n    ".join(parts) + " .")
        OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"  Wrote {OUT.name} ({len(placed)} stones)")
