"""
Wikidata stage: run each declared WikidataSet's SPARQL query against WDQS and
emit the rows as instance triples on the existing ontology -> backend graph
(wikidata.ttl). The Stolperstein pattern, generalised: a large open resource
becomes geocoded, owl:sameAs-linked instances we can hang off the timeline.

Content type: WikidataSet (declared in catalog/wikidata.py). A set's SELECT must
bind ?item (a wd: entity) and ?itemLabel; it may bind ?lat, ?long, ?image, plus
any vars named in `extra`. To keep one row per entity, the query GROUP BYs ?item
and packs multi-valued attributes into ";;"-joined strings (and "QID|Label" pairs
for linked entities); the `extra` spec says how to unpack each back into triples.

Build-time reconciliation: if an entity's Wikidata Q-id matches a hand-authored
Place's `same_as` field, enrichment triples are emitted directly onto id:<slug>
instead of minting a duplicate id:wd_<key>_<nnn> node. The two nodes merge at
Jena load time because they share the same IRI.

Re-runnable; overwrites the TTL.
"""
from dataclasses import dataclass
from typing import Optional

from ..core import BACKEND_GRAPH, Stage, content, register_content, register_stage
from ..graph import model
from ..sources import wikidata

OUT = BACKEND_GRAPH / "wikidata.ttl"
SEP = ";;"   # multi-value separator inside a GROUP_CONCAT cell


@dataclass
class WikidataSet:
    key: str                    # IRI/group key -> id:wd_<key>_<nnn>
    label: str                  # human description (logging only)
    query: str                  # SPARQL SELECT (?item, ?itemLabel[, ?lat ?long ?image, extras])
    cls: str = "Place"          # nmg class for the emitted instances
    about: Optional[str] = None  # event slug -> nmg:about (like the stones -> deportatie)
    geo_required: bool = True   # drop rows without coordinates
    # How to turn extra bound vars into triples. Each entry: (var, kind, *preds).
    #   ("years",  "years",  inception_pred, renovation_pred)  earliest -> inception,
    #                                                           the rest -> renovation
    #   ("arch",   "links",  pred)   "QID|Label;;…" -> one `pred wd:QID` each, + a
    #                                deduped `wd:QID a nmg:Person ; rdfs:label …`
    #   ("style",  "litset", pred)   "a;;b" -> one `pred "a"@nl` per distinct value
    #   ("mid",    "lit",    pred)   single plain literal
    extra: tuple = ()

    def __post_init__(self):
        register_content("wikidata", self)


def _esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _image_url(url):
    """Normalise a P18 Special:FilePath value to an https 320px thumbnail."""
    url = url.replace("http://", "https://", 1)
    return url if "?" in url else url + "?width=320"


def _split(val):
    return [p for p in val.split(SEP) if p.strip()]


def _collect(rows):
    """Index WDQS rows by ?item, keeping the first non-empty value per var
    (queries GROUP BY ?item, so there is already one row per entity)."""
    items = {}
    for r in rows:
        qid = r.get("item")
        if not qid:
            continue
        it = items.setdefault(qid, {})
        for k, v in r.items():
            if v and k not in it:
                it[k] = v
        it.setdefault("label", r.get("itemLabel", qid))
    return list(items.items())


@register_stage
class WikidataStage(Stage):
    name = "wikidata"
    help = "Wikidata SPARQL sets -> instance triples -> backend graph"

    def run(self, args):
        # Reconciliation map: Wikidata Q-id -> authored place slug.
        # Populated by catalog discovery (import_submodules(catalog) in __main__
        # _discover()) before any stage runs, so model.PLACES is complete here.
        qid_to_slug = {
            p.same_as: slug
            for slug, p in model.PLACES.items()
            if p.same_as
        }

        lines = [
            "# Wikidata-sourced instances — one per entity, on the existing ontology.",
            "# Generated by datacollect (wikidata stage) from the Wikidata Query",
            "# Service (CC0). Pure instance triples; owl:sameAs links back to wd:.",
            "# Entities whose Q-id matches an authored Place are merged onto that",
            "# place's IRI (id:<slug>) instead of minting a new id:wd_<key>_<nnn>.",
            "@prefix nmg:    <https://nijmegenkaart.nl/ns#> .",
            "@prefix id:     <https://nijmegenkaart.nl/id/> .",
            "@prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#> .",
            "@prefix owl:    <http://www.w3.org/2002/07/owl#> .",
            "@prefix xsd:    <http://www.w3.org/2001/XMLSchema#> .",
            "@prefix wd:     <http://www.wikidata.org/entity/> .",
            "",
        ]
        agents = {}    # wd QID -> label, for referenced architects/firms (deduped)
        total_minted = 0
        total_merged = 0

        for s in content("wikidata"):
            print(f"  Querying {s.key} ({s.label})…")
            all_items = _collect(wikidata.select(s.query))
            # Matched entities don't need Wikidata coords (authored place has them).
            # Unmatched entities still respect geo_required.
            merged = [(q, it) for q, it in all_items if q in qid_to_slug]
            fresh  = [(q, it) for q, it in all_items
                      if q not in qid_to_slug and (it.get("lat") or not s.geo_required)]
            print(f"    {len(all_items)} entities — "
                  f"{len(fresh)} minted, {len(merged)} merged onto authored")

            lines.append(f"# --- {s.key}: {s.label} "
                         f"({len(fresh)} minted, {len(merged)} merged onto authored) ---")

            # -- Freshly minted instances (unmatched entities) --
            for i, (qid, it) in enumerate(fresh, 1):
                parts = [
                    f"id:wd_{s.key}_{i:03d} a nmg:{s.cls}",
                    f'rdfs:label "{_esc(it["label"])}"@nl',
                    f"owl:sameAs wd:{qid}",
                    f'nmg:wikidataSet "{s.key}"',
                ]
                if it.get("lat") and it.get("long"):
                    parts.append(f"nmg:lat {it['lat']} ; nmg:long {it['long']}")
                if s.about:
                    parts.append(f"nmg:about id:{s.about}")
                if it.get("image"):
                    parts.append(f'nmg:image "{_image_url(it["image"])}"')
                for var, kind, *preds in s.extra:
                    val = it.get(var)
                    if not val:
                        continue
                    if kind == "years":
                        inc, ren = preds
                        ys = sorted({int(y) for y in _split(val)})
                        parts.append(f'{inc} "{ys[0]}"^^xsd:gYear')
                        parts += [f'{ren} "{y}"^^xsd:gYear' for y in ys[1:]]
                    elif kind == "links":
                        for piece in _split(val):
                            pq, _, plabel = piece.partition("|")
                            parts.append(f"{preds[0]} wd:{pq}")
                            agents.setdefault(pq, plabel or pq)
                    elif kind == "litset":
                        for v in dict.fromkeys(_split(val)):
                            parts.append(f'{preds[0]} "{_esc(v)}"@nl')
                    elif kind == "lit":
                        parts.append(f'{preds[0]} "{_esc(val)}"')
                lines.append(" ;\n    ".join(parts) + " .")

            # -- Enrichment merged onto authored places (matched entities) --
            # No lat/long, label, rdf:type, or owl:sameAs — the authored place
            # already declares those. Only wikidataSet + image + extra triples.
            if merged:
                lines.append(f"# --- {s.key}: enrichment merged onto "
                             f"{len(merged)} authored place(s) ---")
                for qid, it in merged:
                    slug = qid_to_slug[qid]
                    parts = [f'id:{slug} nmg:wikidataSet "{s.key}"']
                    if it.get("image"):
                        parts.append(f'nmg:image "{_image_url(it["image"])}"')
                    for var, kind, *preds in s.extra:
                        val = it.get(var)
                        if not val:
                            continue
                        if kind == "years":
                            inc, ren = preds
                            ys = sorted({int(y) for y in _split(val)})
                            parts.append(f'{inc} "{ys[0]}"^^xsd:gYear')
                            parts += [f'{ren} "{y}"^^xsd:gYear' for y in ys[1:]]
                        elif kind == "links":
                            for piece in _split(val):
                                pq, _, plabel = piece.partition("|")
                                parts.append(f"{preds[0]} wd:{pq}")
                                agents.setdefault(pq, plabel or pq)
                        elif kind == "litset":
                            for v in dict.fromkeys(_split(val)):
                                parts.append(f'{preds[0]} "{_esc(v)}"@nl')
                        elif kind == "lit":
                            parts.append(f'{preds[0]} "{_esc(val)}"')
                    lines.append(" ;\n    ".join(parts) + " .")

            total_minted += len(fresh)
            total_merged += len(merged)

        if agents:
            lines.append("")
            lines.append(f"# Architects / firms referenced above ({len(agents)}).")
            for q, lbl in sorted(agents.items()):
                lines.append(f'wd:{q} rdfs:label "{_esc(lbl)}"@nl .')

        OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"  Wrote {OUT.name} ({total_minted} minted, {total_merged} merged onto authored, "
              f"{len(agents)} architects, {len(content('wikidata'))} set(s))")
